In [1]:
import cv2
import numpy as np
import os
import glob

CHECKERBOARD = (7,9)
criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 20, 0.001)


objpoints = []

imgpoints = [] 


objp = np.zeros((1, CHECKERBOARD[0] * CHECKERBOARD[1], 3), np.float32)
objp[0,:,:2] = np.mgrid[0:CHECKERBOARD[0], 0:CHECKERBOARD[1]].T.reshape(-1, 2)
prev_img_shape = None

images = glob.glob('./images/*.jpg')
for fname in images:
    img = cv2.imread(fname)
    img = cv2.resize(img, (604, 806)) 
    gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

    ret, corners = cv2.findChessboardCorners(gray, CHECKERBOARD, cv2.CALIB_CB_ADAPTIVE_THRESH + cv2.CALIB_CB_FAST_CHECK + cv2.CALIB_CB_NORMALIZE_IMAGE)
   
    if ret == True:
        objpoints.append(objp)

        corners2 = cv2.cornerSubPix(gray, corners, (11,11),(-1,-1), criteria)
        
        imgpoints.append(corners2)

        img = cv2.drawChessboardCorners(img, CHECKERBOARD, corners2, ret)
    
    cv2.imshow('img',img)
    cv2.waitKey(0)

cv2.destroyAllWindows()

h,w = img.shape[:2]


ret, mtx, dist, rvecs, tvecs = cv2.calibrateCamera(objpoints, imgpoints, gray.shape[::-1], None, None)

print("Camera matrix : \n")
print(mtx)
print("dist : \n")
print(dist)
print("rvecs : \n")
print(rvecs)
print("tvecs : \n")
print(tvecs)


Camera matrix : 

[[628.15696872   0.         308.88131393]
 [  0.         630.52551993 385.34099043]
 [  0.           0.           1.        ]]
dist : 

[[ 3.35132581e-01 -1.99496027e+00 -2.27449501e-03  1.04656897e-03
   3.42317370e+00]]
rvecs : 

(array([[ 0.04648505],
       [-0.29467678],
       [-0.02899999]]), array([[ 0.3252364 ],
       [-0.32354763],
       [ 0.0167304 ]]), array([[-0.04003587],
       [ 0.26868462],
       [-0.04348229]]), array([[ 0.00120534],
       [ 0.48626286],
       [-0.01569636]]), array([[ 0.30304456],
       [-0.07579546],
       [ 0.02178025]]), array([[ 0.18330208],
       [-0.17402587],
       [ 0.03553238]]), array([[ 0.01115407],
       [-0.38839415],
       [ 0.0764926 ]]), array([[-0.13771106],
       [-0.06357503],
       [-0.01036122]]), array([[-0.07346527],
       [-0.30340833],
       [ 0.03468685]]), array([[-0.20715898],
       [ 0.19128252],
       [ 0.03104957]]), array([[ 0.00720028],
       [ 0.4172603 ],
       [-0.0581364 ]]), a